/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package seguridad.vista;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.ListModel;
import javax.swing.table.DefaultTableModel;
import seguridad.dominio.Aplicacion;
import seguridad.dominio.Perfil;
import seguridad.dominio.Asignacion_Aplicacion_Perfil;
import seguridad.datos.AplicacionDAO;
import seguridad.datos.PerfilDAO;
import seguridad.datos.Asignacion_Aplicacion_PerfilDAO;

/**
 *
 * @author leelu
 */
public class Aplicacion_Perfil extends javax.swing.JInternalFrame {
    DefaultTableModel modelo1;
    DefaultTableModel modelo2; 
        int estadovalidacion;

    /**
     * Creates new form Perfil_App
     */
    public Aplicacion_Perfil() {
        initComponents();
        String perfil;
        PerfilDAO personaDAO = new PerfilDAO();
        List<Perfil> perfiles = personaDAO.select();
        for (Perfil persona : perfiles) {
           
           consulta_perfil.addItem(String.valueOf(persona.getPk_id_perfil()));
        }
        
        modelo1=new DefaultTableModel();   //ASIGNAMOS UN NUEVO DEFAULTABLEMODEL AL OBJETO MODELO1
        modelo1.addColumn("CODIGO");      //LE AÑADIMOS COLUMNAS AL OBJETO MODELO
        modelo1.addColumn("NOMBRE");
        tabla1.setModel(modelo1);
        modelo2=new DefaultTableModel();
        modelo2.addColumn("ID PERFIL");
        modelo2.addColumn("ID APLICACION");
        modelo2.addColumn("INGRESAR");
        modelo2.addColumn("CONSULTAR");
        modelo2.addColumn("MODIFICAR");
        modelo2.addColumn("ELIMINAR");
        modelo2.addColumn("IMPRIMIR");
        tabla2.setModel(modelo2);
        AplicacionDAO dao =new AplicacionDAO();
        dao.select2();  
    }
    
public void LimpiarTabla2(){
        modelo2=new DefaultTableModel();   //ASIGNAMOS UN NUEVO DEFAULTABLEMODEL AL OBJETO MODELO1
    
       modelo2.addColumn("ID PERFIL");
        modelo2.addColumn("ID APLICACION");
        modelo2.addColumn("INGRESAR");
        modelo2.addColumn("CONSULTAR");
        modelo2.addColumn("MODIFICAR");
        modelo2.addColumn("ELIMINAR");
        modelo2.addColumn("IMPRIMIR");
        tabla2.setModel(modelo2);         //LE SETEAMOS EL OBJETO MODELO1 (TABLEMODEL) A LA TABLA (JTABLE) 
    } 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_Nombre_Perfil = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Boton_Buscar_Perfil = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        consulta_perfil = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla2 = new javax.swing.JTable();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setVisible(true);

        txt_Nombre_Perfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Nombre_PerfilActionPerformed(evt);
            }
        });

        jLabel1.setText("Aplicaciones Disponibles");

        jLabel2.setText("Aplicaciones Asignadas");

        jLabel3.setText("Perfil Asignado");

        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel4.setText("Guardar");

        jLabel5.setText("Quitar");

        jLabel6.setText("Asignar");

        Boton_Buscar_Perfil.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Boton_Buscar_Perfil.setText("?");
        Boton_Buscar_Perfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_Buscar_PerfilActionPerformed(evt);
            }
        });

        jButton1.setText(">");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText(">>");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("<");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("<<");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        consulta_perfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consulta_perfilActionPerformed(evt);
            }
        });

        tabla1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CODIGO", "NOMBRE"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabla1);

        tabla2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tabla2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jButton2)
                                            .addComponent(jLabel5)
                                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jButton4)
                                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel4)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 465, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(consulta_perfil, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(Boton_Buscar_Perfil)
                        .addGap(18, 18, 18)
                        .addComponent(txt_Nombre_Perfil)
                        .addGap(198, 198, 198))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_Nombre_Perfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(consulta_perfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Boton_Buscar_Perfil))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_Nombre_PerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Nombre_PerfilActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txt_Nombre_PerfilActionPerformed

    private void Boton_Buscar_PerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_Buscar_PerfilActionPerformed
        LimpiarTabla2();
        String valor=consulta_perfil.getSelectedItem().toString();
        int valorint=Integer.parseInt(valor);
        PerfilDAO perfilDAO = new PerfilDAO();
        Perfil perfilconsultar = new Perfil();
        perfilconsultar.setPk_id_perfil(valorint);
        perfilconsultar=perfilDAO.query(perfilconsultar);
        if (perfilconsultar.getEstado_perfil()!=0) {
            estadovalidacion=1;
            txt_Nombre_Perfil.setText(perfilconsultar.getNombre_perfil());
        }else{
            JOptionPane.showMessageDialog(null, "Perfil no encontrado");
            estadovalidacion=0;
        }
        
//----------------------------------------------------------------------------------------//
                
String combobox=consulta_perfil.getSelectedItem().toString();
int validar=Integer.parseInt(combobox);
String datos[]= new String[7];
        Asignacion_Aplicacion_PerfilDAO dao = new  Asignacion_Aplicacion_PerfilDAO();
        List<Asignacion_Aplicacion_Perfil> personas = dao.select2();
        for (Asignacion_Aplicacion_Perfil persona : personas) {       
            if (validar==Integer.parseInt(persona.getCodigo_Perfil())) {
               
               datos[0]=persona.getCodigo_Perfil();
               datos[1]=persona.getCodigo_Aplicacion();
               datos[2]=persona.getImprimir();
               datos[3]=persona.getModificar();
               datos[4]=persona.getEliminar();
               datos[5]=persona.getIngresar();
               datos[6]=persona.getConsultar();
               
                modelo2.addRow(datos);
        tabla2.setModel(modelo2);
            }            
        }
        
//----------------------------------------------------------------------------------------//


        
    }//GEN-LAST:event_Boton_Buscar_PerfilActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
int filaSeleccionada=tabla1.getSelectedRow();  //LE ASIGNAMOS UNA VARIABLE INTEGER A LA FILA SELECCIONADA EN LA TABLA
        if (estadovalidacion==1) {
        if(filaSeleccionada>=0){   //SI EXISTE UNA FILA SELECCIONADA REALIZARA EL TRASPASO
            
               String Vector[]=new String[2];   //CREAR UN VECTOR
                //LE ASIGNAMOS AL VECTOR Y CAPTURAMOS LOS DATOS DE LA TABLA1 EN LA FILA SELECCIONADA EN LA POSICION 0 Y 1,
                //ES DECIR COLUMNA NOMBRES Y APELLIDOS
               Vector[0]=tabla1.getValueAt(filaSeleccionada, 0).toString();
               Vector[1]=consulta_perfil.getSelectedItem().toString();
               modelo2.addRow(Vector); 
               
               
                  //LLAMAMOS AL MODELO DE LA PANTALLA2 Y LE AGREGAMOS EL VECTOR COMO UNA NUEVA FILA
        }    
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
for (int i = 0; i < tabla1.getRowCount(); i++) {
            String Vector[]=new String[2];
            Vector[0]=tabla1.getValueAt(i, 0).toString();
            Vector[1]=consulta_perfil.getSelectedItem().toString();
            
            modelo2.addRow(Vector);    //LLAMAMOS AL MODELO DE LA PANTALLA2 Y LE AGREGAMOS EL VECTOR COMO UNA NUEVA FILA
            
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
int filaSeleccionada=tabla2.getSelectedRow();  //LE ASIGNAMOS UNA VARIABLE INTEGER A LA FILA SELECCIONADA EN LA TABLA
        
        if(filaSeleccionada>=0){   //SI EXISTE UNA FILA SELECCIONADA REALIZARA EL TRASPASO
            
               String Vector[]=new String[2];   //CREAR UN VECTOR
                //LE ASIGNAMOS AL VECTOR Y CAPTURAMOS LOS DATOS DE LA TABLA1 EN LA FILA SELECCIONADA EN LA POSICION 0 Y 1,
                //ES DECIR COLUMNA NOMBRES Y APELLIDOS
               Vector[0]=tabla2.getValueAt(filaSeleccionada, 0).toString();    
               Vector[1]=tabla2.getValueAt(filaSeleccionada, 1).toString();
               
               
               modelo1.addRow(Vector);    //LLAMAMOS AL MODELO DE LA PANTALLA2 Y LE AGREGAMOS EL VECTOR COMO UNA NUEVA FILA
               modelo2.removeRow(filaSeleccionada);  //ELIMINAMOS LA FILA TRASPASADA DE LA PANTALLA1
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
    LimpiarTabla2();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void consulta_perfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consulta_perfilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_consulta_perfilActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

    }//GEN-LAST:event_jButton5ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Boton_Buscar_Perfil;
    private javax.swing.JComboBox<String> consulta_perfil;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JTable tabla1;
    private javax.swing.JTable tabla2;
    private javax.swing.JTextField txt_Nombre_Perfil;
    // End of variables declaration//GEN-END:variables
}
