package seguridad.vista;

import com.formdev.flatlaf.FlatDarkLaf;
import java.awt.Graphics;
import java.awt.Image;
import java.net.UnknownHostException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import seguridad.dominio.Usuario;
import seguridad.datos.PerfilDAO;
import seguridad.dominio.Perfil;
import seguridad.dominio.Usuario;

/**
 *
 * @author Diego Vásquez
 */
public class MDI_Sistema extends javax.swing.JFrame {
    
    private Aplicacion_Perfil NuevaVentana;

    private Mantenimiento_Modulos formMantenimiento_Modulo;
    private Mantenimiento_Aplicacion formMantenimiento_Aplicacion;
    private Asignacion_modulos formModulos;

    private Mantenimiento_Perfil formMantenimiento_Perfil;

    /**
     * Creates new form MDI_Seguridad
     *
     * @throws java.net.UnknownHostException
     */
    MDI_Components mdi_components = new MDI_Components();

    /* ---- PERMISOS MODULOS: DIEGO VÁSQUEZ ----*/
    Usuario objUsuario = new Usuario();

    public MDI_Sistema(Usuario objUsuario) {
        initComponents();

        setLocationRelativeTo(null);
        this.objUsuario = objUsuario;
        String id_Usuario = objUsuario.getId_usuario();

        int id_perfil = 0;
        int id_Usuario = objUsuario.getId_usuario();
        
        int id_perfil=0;
        

        //PENDIENTE
        /*
        Perfil objPerfil = new Perfil();
        PerfilDAO perfilDAO = new PerfilDAO();
        objPerfil.setFk_Usuario(id_Usuario);
        perfilDAO.query(objPerfil);
        id_perfil = objPerfil.getId_Perfil();
        */

       
        Perfil objPerfil = new Perfil();
        PerfilDAO perfilDAO = new PerfilDAO();
        //objPerfil.setFk_Usuario(id_Usuario);
        perfilDAO.query(objPerfil);
        id_perfil = objPerfil.getPk_id_perfil();

        switch (id_perfil) {
            case 1:
                break;
        }

    }

    /*------------------------------------------*/
    public MDI_Sistema() throws UnknownHostException {
        initComponents();
        this.setTitle("Usuario: " + "[" + "]" + " \t" + "IP: [" + mdi_components.getIp() + "]");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JDesktopPane_Escritorio = new javax.swing.JDesktopPane()
        ;
        jMenuBar1 = new javax.swing.JMenuBar();
        JMenu_Archivo = new javax.swing.JMenu();
        JMenuItem_CerrarSesion = new javax.swing.JMenuItem();
        JMenu_Seguridad = new javax.swing.JMenu();
        JMenu_Asignaciones = new javax.swing.JMenu();
        JMenuItem_ApU = new javax.swing.JMenuItem();
        JMenuItem_ApP = new javax.swing.JMenuItem();
        JMenuItem_PU = new javax.swing.JMenuItem();
        JMenuItem_ApM = new javax.swing.JMenuItem();
        JMenuItem_Bitacora = new javax.swing.JMenuItem();
        JMenu_Mantenimientos = new javax.swing.JMenu();
        JMenuItem_Usuarios = new javax.swing.JMenuItem();
        JMenuItem_Aplicaciones = new javax.swing.JMenuItem();
        JMenuItem_Perfiles = new javax.swing.JMenuItem();
        JMenuItem_Modulos = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema Hotelero");
        setResizable(false);

        javax.swing.GroupLayout JDesktopPane_EscritorioLayout = new javax.swing.GroupLayout(JDesktopPane_Escritorio);
        JDesktopPane_Escritorio.setLayout(JDesktopPane_EscritorioLayout);
        JDesktopPane_EscritorioLayout.setHorizontalGroup(
            JDesktopPane_EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1350, Short.MAX_VALUE)
        );
        JDesktopPane_EscritorioLayout.setVerticalGroup(
            JDesktopPane_EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 726, Short.MAX_VALUE)
        );

        JMenu_Archivo.setText("Archivo");
        JMenu_Archivo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        JMenuItem_CerrarSesion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        JMenuItem_CerrarSesion.setText("Cerrar Sesión");
        JMenuItem_CerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMenuItem_CerrarSesionActionPerformed(evt);
            }
        });
        JMenu_Archivo.add(JMenuItem_CerrarSesion);

        jMenuBar1.add(JMenu_Archivo);

        JMenu_Seguridad.setText("Seguridad");
        JMenu_Seguridad.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        JMenu_Asignaciones.setText("Asignaciones");
        JMenu_Asignaciones.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        JMenuItem_ApU.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        JMenuItem_ApU.setText("Aplicaciones - Usuario");
        JMenu_Asignaciones.add(JMenuItem_ApU);

        JMenuItem_ApP.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        JMenuItem_ApP.setText("Aplicaciones - Perfiles");
        JMenuItem_ApP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMenuItem_ApPActionPerformed(evt);
            }
        });
        JMenu_Asignaciones.add(JMenuItem_ApP);

        JMenuItem_PU.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        JMenuItem_PU.setText("Perfiles - Usuarios");
        JMenu_Asignaciones.add(JMenuItem_PU);

        JMenuItem_ApM.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        JMenuItem_ApM.setText("Aplicaciones - Módulos");
        JMenuItem_ApM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMenuItem_ApMActionPerformed(evt);
            }
        });
        JMenu_Asignaciones.add(JMenuItem_ApM);

        JMenu_Seguridad.add(JMenu_Asignaciones);

        JMenuItem_Bitacora.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        JMenuItem_Bitacora.setText("Bitácora");
        JMenu_Seguridad.add(JMenuItem_Bitacora);

        JMenu_Mantenimientos.setText("Mantenimientos");
        JMenu_Mantenimientos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        JMenuItem_Usuarios.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        JMenuItem_Usuarios.setText("Usuarios");
        JMenuItem_Usuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMenuItem_UsuariosActionPerformed(evt);
            }
        });
        JMenu_Mantenimientos.add(JMenuItem_Usuarios);

        JMenuItem_Aplicaciones.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        JMenuItem_Aplicaciones.setText("Aplicaciones");
        JMenuItem_Aplicaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMenuItem_AplicacionesActionPerformed(evt);
            }
        });
        JMenu_Mantenimientos.add(JMenuItem_Aplicaciones);

        JMenuItem_Perfiles.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        JMenuItem_Perfiles.setText("Perfiles");
        JMenuItem_Perfiles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMenuItem_PerfilesActionPerformed(evt);
            }
        });
        JMenu_Mantenimientos.add(JMenuItem_Perfiles);

        JMenuItem_Modulos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        JMenuItem_Modulos.setText("Módulos");
        JMenuItem_Modulos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMenuItem_ModulosActionPerformed(evt);
            }
        });
        JMenu_Mantenimientos.add(JMenuItem_Modulos);

        JMenu_Seguridad.add(JMenu_Mantenimientos);

        jMenu1.setText("Cambio Contraseña");
        jMenu1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        JMenu_Seguridad.add(jMenu1);

        jMenuBar1.add(JMenu_Seguridad);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JDesktopPane_Escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JDesktopPane_Escritorio, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    private void JMenuItem_CerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenuItem_CerrarSesionActionPerformed
        /*===== OPERACIÓN CERRAR SESIÓN ====
          Variable entera respuesta_cs*/

        int respuesta_cs = JOptionPane.showConfirmDialog(this, "¿Desea Cerrar Sesión?", "Cerrar Sesión", JOptionPane.YES_NO_OPTION);

        if (respuesta_cs == 0) {
            this.dispose();
        }
    }//GEN-LAST:event_JMenuItem_CerrarSesionActionPerformed


    private void JMenuItem_ModulosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenuItem_ModulosActionPerformed
        formMantenimiento_Modulo = new Mantenimiento_Modulos();
        formMantenimiento_Modulo.setVisible(true);
        JDesktopPane_Escritorio.add(formMantenimiento_Modulo);
    }//GEN-LAST:event_JMenuItem_ModulosActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        formMantenimiento_Modulo = new Mantenimiento_Modulos();
        JDesktopPane_Escritorio.add(formMantenimiento_Modulo);


    }//GEN-LAST:event_jMenuItem10ActionPerformed


    private void JMenuItem_AplicacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenuItem_AplicacionesActionPerformed
        formMantenimiento_Aplicacion = new Mantenimiento_Aplicacion();
        formMantenimiento_Aplicacion.setVisible(true);
        JDesktopPane_Escritorio.add(formMantenimiento_Aplicacion);
    }//GEN-LAST:event_JMenuItem_AplicacionesActionPerformed

    private void JMenuItem_PerfilesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenuItem_PerfilesActionPerformed
        formMantenimiento_Perfil = new Mantenimiento_Perfil();
        JDesktopPane_Escritorio.add(formMantenimiento_Perfil);

    }//GEN-LAST:event_JMenuItem_PerfilesActionPerformed

    private void JMenuItem_ApPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenuItem_ApPActionPerformed
        // TODO add your handling code here:
        NuevaVentana = new Aplicacion_Perfil();
        JDesktopPane_Escritorio.add(NuevaVentana);
    }//GEN-LAST:event_JMenuItem_ApPActionPerformed

    private void JMenuItem_ApMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenuItem_ApMActionPerformed
        //  Asignacionmodulos Rita Sipaque
        formModulos = new Asignacion_modulos();
        formModulos.setVisible(true);
        JDesktopPane_Escritorio.add(formModulos);
    }//GEN-LAST:event_JMenuItem_ApMActionPerformed

    private void JMenuItem_UsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenuItem_UsuariosActionPerformed
        Mantenimiento_Usuario frm_mantusu = new Mantenimiento_Usuario();
        frm_mantusu.setVisible(true);
        JDesktopPane_Escritorio.add(frm_mantusu);
    }//GEN-LAST:event_JMenuItem_UsuariosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        try {
            UIManager.setLookAndFeel(new FlatDarkLaf());
        } catch (Exception ex) {
            System.out.println(ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new MDI_Sistema().setVisible(true);
                } catch (UnknownHostException ex) {
                    Logger.getLogger(MDI_Sistema.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane JDesktopPane_Escritorio;
    private javax.swing.JMenuItem JMenuItem_ApM;
    private javax.swing.JMenuItem JMenuItem_ApP;
    private javax.swing.JMenuItem JMenuItem_ApU;
    private javax.swing.JMenuItem JMenuItem_Aplicaciones;
    private javax.swing.JMenuItem JMenuItem_Bitacora;
    private javax.swing.JMenuItem JMenuItem_CerrarSesion;
    private javax.swing.JMenuItem JMenuItem_Modulos;
    private javax.swing.JMenuItem JMenuItem_PU;
    private javax.swing.JMenuItem JMenuItem_Perfiles;
    private javax.swing.JMenuItem JMenuItem_Usuarios;
    private javax.swing.JMenu JMenu_Archivo;
    private javax.swing.JMenu JMenu_Asignaciones;
    private javax.swing.JMenu JMenu_Mantenimientos;
    private javax.swing.JMenu JMenu_Seguridad;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
