/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Finanzas.vista;

import Finanzas.dominio.PeriodoFiscal;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import Finanzas.datos.PeriodoFiscalDAO;
import java.util.Date;
import javax.swing.JOptionPane;




/**
 *
 * @author OtakuGT
 */
public class Mantenimiento_PeriodoFiscal extends javax.swing.JInternalFrame {

        
     public void llenadoDeTablas() {
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("ID");
        modelo.addColumn("Inicio Periodo Fiscal");
        modelo.addColumn("Fin Periodo Fiscal");
        modelo.addColumn("Estado Periodo Fiscal");
        PeriodoFiscalDAO PerFisDAO = new PeriodoFiscalDAO();
        List<PeriodoFiscal> PerFis = PerFisDAO.select();
        Tabla.setModel(modelo);
        Object[] objeto = new Object[4];
        for (int i = 0; i < PerFis.size(); i++) {
            objeto[0] = PerFis.get(i).getIDPerFis();
            objeto[1] = PerFis.get(i).getInicioAñoPerFis();
            objeto[2] = PerFis.get(i).getFinAñoPerFis();
            objeto[3] = PerFis.get(i).getEstadoPerFis();

            modelo.addRow(objeto);
        }
    }
     
     public void limpiar() {
        txtID.setText("");
        RBPF1.setSelected(false);
        RBPF0.setSelected(false);
    }
     
     int CodigoAplicacion = 10;
     
     
    /**
     * Creates new form PeriodoFiscal
     */
    public Mantenimiento_PeriodoFiscal() {
        initComponents();
        llenadoDeTablas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        AñoJC = new com.toedter.calendar.JYearChooser();
        jLabel1 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        BtnAgregar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        RBPF1 = new javax.swing.JRadioButton();
        RBPF0 = new javax.swing.JRadioButton();
        jButton4 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Año Periodo Fiscal");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Periodo Fiscal"));
        jPanel1.setToolTipText("");

        jLabel1.setText("ID");

        jLabel2.setText("Año");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel1))
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(AñoJC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AñoJC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap())
        );

        BtnAgregar.setText("Agregar");
        BtnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAgregarActionPerformed(evt);
            }
        });

        jButton2.setText("Eliminar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Buscar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(Tabla);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Estado Periodo Fiscal"));

        buttonGroup1.add(RBPF1);
        RBPF1.setText("Activo");

        buttonGroup1.add(RBPF0);
        RBPF0.setText("Inactivo");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RBPF0)
                    .addComponent(RBPF1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(RBPF1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RBPF0)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton4.setText("Modificar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(BtnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnAgregar)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {BtnAgregar, jButton2, jButton3, jButton4});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAgregarActionPerformed
        PeriodoFiscal PFInsertar = new PeriodoFiscal();
        PeriodoFiscalDAO PFDAO = new PeriodoFiscalDAO();
        int Year = AñoJC.getYear(); 
        int Day = (1);
        int Month = (1);
        int DayEnd = (31);
        int MonthEnd = (12);
        String FechaInicio = String.valueOf(Day + "-" + Month + "-" + Year);
        String FechaFin = String.valueOf(DayEnd + "-" + MonthEnd + "-" + Year);
        if (txtID.getText().length() != 0 && RBPF1.isSelected() || RBPF0.isSelected()) {
            {
                PFInsertar.setIDPerFis(Integer.parseInt(txtID.getText()));
                PFInsertar.setInicioAñoPerFis(FechaInicio);
                PFInsertar.setFinAñoPerFis(FechaFin);
                if (RBPF1.isSelected()) {
                    PFInsertar.setEstadoPerFis(1);
                }
                if (RBPF0.isSelected()) {
                    PFInsertar.setEstadoPerFis(0);
                }
                {
                    JOptionPane.showMessageDialog(null, "Usuario registrado Exitosamente");
                }
                limpiar();
                llenadoDeTablas();
                PFDAO.insert(PFInsertar);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Los campos estan vacios");
            llenadoDeTablas();
        }
        llenadoDeTablas();
    }//GEN-LAST:event_BtnAgregarActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        PeriodoFiscal PFMod = new PeriodoFiscal();
        PeriodoFiscalDAO PFDAO = new PeriodoFiscalDAO();
        int Year = AñoJC.getYear(); 
        int Day = (1);
        int Month = (1);
        int DayEnd = (31);
        int MonthEnd = (12);
        String FechaInicio = String.valueOf(Day + "-" + Month + "-" + Year);
        String FechaFin = String.valueOf(DayEnd + "-" + MonthEnd + "-" + Year);
        PFMod.setIDPerFis(Integer.parseInt(txtID.getText()));
        PFMod.setInicioAñoPerFis(FechaInicio);
        PFMod.setFinAñoPerFis(FechaFin);

        if (RBPF1.isSelected()) {
            PFMod.setEstadoPerFis(1);
        }
        if (RBPF0.isSelected()) {
            PFMod.setEstadoPerFis(0);
        }
        
        PFDAO.update(PFMod);
        JOptionPane.showMessageDialog(null, "Modificación Exitosa");
        llenadoDeTablas();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        PeriodoFiscal PFDel = new PeriodoFiscal();
        PeriodoFiscalDAO PFDAO = new PeriodoFiscalDAO();

        PFDel.setIDPerFis(Integer.parseInt(txtID.getText()));
        PFDAO.delete(PFDel);
        JOptionPane.showMessageDialog(null, "Año Fiscal Eliminado.");
        llenadoDeTablas();
        limpiar();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        PeriodoFiscal PFBuscar = new PeriodoFiscal();
        PeriodoFiscalDAO PFDAO = new PeriodoFiscalDAO();
        PFBuscar.setIDPerFis(Integer.parseInt(txtID.getText()));

        PFBuscar = PFDAO.query(PFBuscar);

        txtID.setText(String.valueOf(PFBuscar.getIDPerFis()));
        AñoJC.setYear(Integer.parseInt(PFBuscar.getInicioAñoPerFis()));

        if (PFBuscar.getEstadoPerFis() == 1) {
            RBPF1.setSelected(true);
        }
        if (PFBuscar.getEstadoPerFis() == 0) {
            RBPF0.setSelected(true);
        }

        {
            JOptionPane.showMessageDialog(null, "Registro encontrado");
        }
        llenadoDeTablas();
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JYearChooser AñoJC;
    private javax.swing.JButton BtnAgregar;
    private javax.swing.JRadioButton RBPF0;
    private javax.swing.JRadioButton RBPF1;
    private javax.swing.JTable Tabla;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtID;
    // End of variables declaration//GEN-END:variables
}
