package Hoteleria.vista;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import Hoteleria.datos.HabitacionesDAO;
import Hoteleria.dominio.Habitaciones;
import java.net.UnknownHostException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import seguridad.vista.Login;

/**
 *
 * @author leone
 */
public class CatalogoDeHabitaciones extends javax.swing.JFrame {

    /**
     * Creates new form CatalogoDeHabitaciones
     */
    public CatalogoDeHabitaciones() throws UnknownHostException {
        initComponents();
        actualizartabla();
        this.setTitle("Usuario: " + "[" + Login.usuarioHoteleria + "]" + " \t" + "IP: [" + LoginMDI.getIp() + "] CATALOGO DE HABITACIONES");
    }
    
    public void actualizartabla(){
        DefaultTableModel modelo1 = new DefaultTableModel(){
            @Override
            public boolean isCellEditable (int row, int column)
                {
                    if (column == 1&&column==2&&column==3&&column==4&&column==5&&column==6)
                       return true;
                    return false;
                }
        };
        DefaultTableCellRenderer centro= new DefaultTableCellRenderer();
        int i;
        
        modelo1.addColumn("ID");
        modelo1.addColumn("Descripcion");
        modelo1.addColumn("Precio Diario");
        modelo1.addColumn("Piso");
        modelo1.addColumn("Estado");
        modelo1.addColumn("Tipo");
        modelo1.addColumn("Cantidad Personas");

        tabla.setModel(modelo1);
        
        centro.setHorizontalAlignment(JLabel.CENTER);
        
        tabla.getColumnModel().getColumn(0).setCellRenderer(centro);
        tabla.getColumnModel().getColumn(1).setCellRenderer(centro);
        tabla.getColumnModel().getColumn(2).setCellRenderer(centro);
        tabla.getColumnModel().getColumn(3).setCellRenderer(centro);
        tabla.getColumnModel().getColumn(4).setCellRenderer(centro);
        tabla.getColumnModel().getColumn(5).setCellRenderer(centro);
        tabla.getColumnModel().getColumn(6).setCellRenderer(centro);
        
        tabla.getColumnModel().getColumn(0).setPreferredWidth(50);        
        tabla.getColumnModel().getColumn(1).setPreferredWidth(200);
        tabla.getColumnModel().getColumn(2).setPreferredWidth(75);        
        tabla.getColumnModel().getColumn(3).setPreferredWidth(25);
        tabla.getColumnModel().getColumn(4).setPreferredWidth(50);        
        tabla.getColumnModel().getColumn(5).setPreferredWidth(75);        
        tabla.getColumnModel().getColumn(6).setPreferredWidth(100);
        
        
        
        String datos[] = new String[7];
        HabitacionesDAO habitacionesDAO = new HabitacionesDAO();
        List<Habitaciones> habitaciones = habitacionesDAO.select();
        for (Habitaciones habitacion : habitaciones) {
            if (habitacion.getEstado_Habitacion()==1) {
            datos[0] = String.valueOf(habitacion.getId_Habitaciones());
            datos[1] = habitacion.getDescripcion();
            datos[2] = String.valueOf(habitacion.getPrecio());
            datos[3] = String.valueOf(habitacion.getPiso());
            datos[4] = "Disponible";
            datos[5] = habitacion.getTipo_Habitacion();
            datos[6] = habitacion.getMax_personas();
            modelo1.addRow(datos);
            tabla.setModel(modelo1);
            }

        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tabla);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 760, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 477, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CatalogoDeHabitaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CatalogoDeHabitaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CatalogoDeHabitaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CatalogoDeHabitaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new CatalogoDeHabitaciones().setVisible(true);
                } catch (UnknownHostException ex) {
                    Logger.getLogger(CatalogoDeHabitaciones.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
