/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Hoteleria.vista;

import Hoteleria.datos.GuardarBitacoraDAO;
import com.formdev.flatlaf.FlatLightLaf;
import java.awt.Dimension;
import java.net.UnknownHostException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import seguridad.vista.GenerarPermisos;
import seguridad.vista.Login;

/**
 *
 * @author Herbert Leonel Dominguez Chavez 9959-19-5644
 */
public class MDIHoteleria extends javax.swing.JFrame {

    private Mantenimiento_AmaDeLlaves formMantenimiento_Ama_De_Llaves;
    private Mantenimiento_habitaciones formMantenimiento_habitaciones;
    private Mantenimiento_FormasDePago formMantenimiento_FormasDePago;
    private Mantenimiento_Servicios formMantenimiento_Servicios;
    private Mantenimiento_Huespedes formMantenimiento_Huespedes;
    private Mantenimiento_Pisos formMantenimiento_Pisos;
    private Asignaciones_Habitaciones fromHabitaciones;
    private ReservaDeHabitacion fromReservaDeHabitacion;
    private FacturacionDeHabitacion fromFacturacionDeHabitacion;
    private ObjetosPerdidos fromObjetosPerdidos;
    private Entregar_objeto fromObjetosPerdidosEnt;
    private BitacoraHotelera formBitacoraH;
    
    public static JLabel logo = new JLabel();

    
    GuardarBitacoraDAO guardaraccion = new GuardarBitacoraDAO();
    /**
     * Creates new form MDIHoteleria
     */
    public MDIHoteleria() throws UnknownHostException {
        initComponents();
        logo(0);
        this.setTitle("Usuario: " + "[" + Login.usuarioHoteleria + "]" + " \t" + "IP: [" + LoginMDI.getIp() + "]");

        GenerarPermisos generarPermisos = new GenerarPermisos();
        var usuario = Login.usuarioHoteleria;
        var modulo = "Hotelero";
        generarPermisos.getPermisos(modulo, usuario);
    }

    public void logo(int activar) {
        Icon icon = new ImageIcon("C:src/main/java/Hoteleria/reportes/Imagen1.png");
        logo.setSize(300, 300);
        if (icon != null) {
            //Agrega Icono
            logo.setIcon(icon);
        } else {
            //No existe imagen.
        }
        Dimension desktopSize = jDesktopPane1.getSize();
        Dimension FrameSize = logo.getSize();
        logo.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
        logo.setVisible(true);
        jDesktopPane1.add(logo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu_archivo = new javax.swing.JMenu();
        menu_catalogos = new javax.swing.JMenu();
        submenu_mantenimientos = new javax.swing.JMenu();
        mnt_amadellaves = new javax.swing.JMenuItem();
        mnt_habitaciones = new javax.swing.JMenuItem();
        mnt_servicios = new javax.swing.JMenuItem();
        mnt_huespedes = new javax.swing.JMenuItem();
        mnt_formasdepago = new javax.swing.JMenuItem();
        mnt_pisos = new javax.swing.JMenuItem();
        menu_procesos = new javax.swing.JMenu();
        submenu_procesos = new javax.swing.JMenu();
        Entregar_Recibir_Habitacion = new javax.swing.JMenuItem();
        Reserva_De_Habitacion = new javax.swing.JMenuItem();
        Facturacion = new javax.swing.JMenuItem();
        Objetos_Perdidos = new javax.swing.JMenuItem();
        Entrega_Objetos_Perdidos = new javax.swing.JMenuItem();
        menu_informes = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        menu_herramientas = new javax.swing.JMenu();
        menu_ayuda = new javax.swing.JMenu();
        cerrar_sesion = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jDesktopPane1.setBackground(new java.awt.Color(228, 68, 68));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1356, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 701, Short.MAX_VALUE)
        );

        jMenuBar1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N

        menu_archivo.setText("Archivo");
        menu_archivo.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jMenuBar1.add(menu_archivo);

        menu_catalogos.setText("Catálogos");
        menu_catalogos.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N

        submenu_mantenimientos.setText("Mantenimientos");

        mnt_amadellaves.setText("Mantenimiento Ama de Llaves");
        mnt_amadellaves.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnt_amadellavesActionPerformed(evt);
            }
        });
        submenu_mantenimientos.add(mnt_amadellaves);

        mnt_habitaciones.setText("Mantenimiento Habitaciones");
        mnt_habitaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnt_habitacionesActionPerformed(evt);
            }
        });
        submenu_mantenimientos.add(mnt_habitaciones);

        mnt_servicios.setText("Mantenimiento de Servicios");
        mnt_servicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnt_serviciosActionPerformed(evt);
            }
        });
        submenu_mantenimientos.add(mnt_servicios);

        mnt_huespedes.setText("Mantenimiento de Huespedes");
        mnt_huespedes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnt_huespedesActionPerformed(evt);
            }
        });
        submenu_mantenimientos.add(mnt_huespedes);

        mnt_formasdepago.setText("Mantenimiento de Formas de Pago");
        mnt_formasdepago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnt_formasdepagoActionPerformed(evt);
            }
        });
        submenu_mantenimientos.add(mnt_formasdepago);

        mnt_pisos.setText("Mantenimiento de Pisos");
        mnt_pisos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnt_pisosActionPerformed(evt);
            }
        });
        submenu_mantenimientos.add(mnt_pisos);

        menu_catalogos.add(submenu_mantenimientos);

        jMenuBar1.add(menu_catalogos);

        menu_procesos.setText("Procesos");
        menu_procesos.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N

        submenu_procesos.setText("Procesos");

        Entregar_Recibir_Habitacion.setText("asignacion de habitaciones");
        Entregar_Recibir_Habitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Entregar_Recibir_HabitacionActionPerformed(evt);
            }
        });
        submenu_procesos.add(Entregar_Recibir_Habitacion);

        Reserva_De_Habitacion.setText("Reserva de Habitacion");
        Reserva_De_Habitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Reserva_De_HabitacionActionPerformed(evt);
            }
        });
        submenu_procesos.add(Reserva_De_Habitacion);

        Facturacion.setText("Facturación");
        Facturacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FacturacionActionPerformed(evt);
            }
        });
        submenu_procesos.add(Facturacion);

        Objetos_Perdidos.setText("Objetos Perdidos");
        Objetos_Perdidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Objetos_PerdidosActionPerformed(evt);
            }
        });
        submenu_procesos.add(Objetos_Perdidos);

        Entrega_Objetos_Perdidos.setText("Entregar Obj Perdido");
        Entrega_Objetos_Perdidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Entrega_Objetos_PerdidosActionPerformed(evt);
            }
        });
        submenu_procesos.add(Entrega_Objetos_Perdidos);

        menu_procesos.add(submenu_procesos);

        jMenuBar1.add(menu_procesos);

        menu_informes.setText("Informes");
        menu_informes.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N

        jMenuItem1.setText("Historial de Bitacora");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menu_informes.add(jMenuItem1);

        jMenuBar1.add(menu_informes);

        menu_herramientas.setText("Herramientas");
        menu_herramientas.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jMenuBar1.add(menu_herramientas);

        menu_ayuda.setText("Ayuda");
        menu_ayuda.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jMenuBar1.add(menu_ayuda);

        cerrar_sesion.setText("Cerrar Sesión");
        cerrar_sesion.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        cerrar_sesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cerrar_sesionMouseClicked(evt);
            }
        });
        jMenuBar1.add(cerrar_sesion);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mnt_amadellavesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnt_amadellavesActionPerformed
        formMantenimiento_Ama_De_Llaves = new Mantenimiento_AmaDeLlaves();
        formMantenimiento_Ama_De_Llaves.setVisible(true);

        jDesktopPane1.add(formMantenimiento_Ama_De_Llaves);
        Dimension desktopSize = jDesktopPane1.getSize();
        Dimension FrameSize = formMantenimiento_Ama_De_Llaves.getSize();
        formMantenimiento_Ama_De_Llaves.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
        formMantenimiento_Ama_De_Llaves.show();
        
        guardaraccion.GuardarEnBitacora("Acceso","2001", Login.usuarioHoteleria);
        logo.setVisible(false);
    }//GEN-LAST:event_mnt_amadellavesActionPerformed

    private void mnt_habitacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnt_habitacionesActionPerformed
        formMantenimiento_habitaciones = new Mantenimiento_habitaciones();

        jDesktopPane1.add(formMantenimiento_habitaciones);
        Dimension desktopSize = jDesktopPane1.getSize();
        Dimension FrameSize = formMantenimiento_habitaciones.getSize();
        formMantenimiento_habitaciones.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
        formMantenimiento_habitaciones.setVisible(true);
        guardaraccion.GuardarEnBitacora("Acceso","2003", Login.usuarioHoteleria);
        logo.setVisible(false);
    }//GEN-LAST:event_mnt_habitacionesActionPerformed

    private void mnt_serviciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnt_serviciosActionPerformed
        formMantenimiento_Servicios = new Mantenimiento_Servicios();

        jDesktopPane1.add(formMantenimiento_Servicios);
        Dimension desktopSize = jDesktopPane1.getSize();
        Dimension FrameSize = formMantenimiento_Servicios.getSize();
        formMantenimiento_Servicios.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
        formMantenimiento_Servicios.setVisible(true);
        guardaraccion.GuardarEnBitacora("Acceso","2006", Login.usuarioHoteleria);
        logo.setVisible(false);
    }//GEN-LAST:event_mnt_serviciosActionPerformed

    private void mnt_huespedesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnt_huespedesActionPerformed
        formMantenimiento_Huespedes = new Mantenimiento_Huespedes();

        jDesktopPane1.add(formMantenimiento_Huespedes);
        Dimension desktopSize = jDesktopPane1.getSize();
        Dimension FrameSize = formMantenimiento_Huespedes.getSize();
        formMantenimiento_Huespedes.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
        formMantenimiento_Huespedes.setVisible(true);
        guardaraccion.GuardarEnBitacora("Acceso","2004", Login.usuarioHoteleria);
        logo.setVisible(false);
    }//GEN-LAST:event_mnt_huespedesActionPerformed

    private void mnt_formasdepagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnt_formasdepagoActionPerformed
        formMantenimiento_FormasDePago = new Mantenimiento_FormasDePago();

        jDesktopPane1.add(formMantenimiento_FormasDePago);
        Dimension desktopSize = jDesktopPane1.getSize();
        Dimension FrameSize = formMantenimiento_FormasDePago.getSize();
        formMantenimiento_FormasDePago.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
        formMantenimiento_FormasDePago.setVisible(true);
        guardaraccion.GuardarEnBitacora("Acceso","2002", Login.usuarioHoteleria);
        logo.setVisible(false);
    }//GEN-LAST:event_mnt_formasdepagoActionPerformed

    private void mnt_pisosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnt_pisosActionPerformed
        formMantenimiento_Pisos = new Mantenimiento_Pisos();

        jDesktopPane1.add(formMantenimiento_Pisos);
        Dimension desktopSize = jDesktopPane1.getSize();
        Dimension FrameSize = formMantenimiento_Pisos.getSize();
        formMantenimiento_Pisos.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
        formMantenimiento_Pisos.setVisible(true);
        guardaraccion.GuardarEnBitacora("Acceso","2005", Login.usuarioHoteleria);
        logo.setVisible(false);
    }//GEN-LAST:event_mnt_pisosActionPerformed

    private void cerrar_sesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrar_sesionMouseClicked
        int respuesta_cs = JOptionPane.showConfirmDialog(this, "¿Desea Cerrar Sesión?", "Cerrar Sesión", JOptionPane.YES_NO_OPTION);

        if (respuesta_cs == 0) {
            this.dispose();
            guardaraccion.GuardarEnBitacora("Salir","2000", Login.usuarioHoteleria);
        }
    }//GEN-LAST:event_cerrar_sesionMouseClicked

    private void Entregar_Recibir_HabitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Entregar_Recibir_HabitacionActionPerformed
        fromHabitaciones = new Asignaciones_Habitaciones();

        jDesktopPane1.add(fromHabitaciones);
        Dimension desktopSize = jDesktopPane1.getSize();
        Dimension FrameSize = fromHabitaciones.getSize();
        fromHabitaciones.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
        fromHabitaciones.setVisible(true);
        guardaraccion.GuardarEnBitacora("Acceso","2202", Login.usuarioHoteleria);
        logo.setVisible(false);
    }//GEN-LAST:event_Entregar_Recibir_HabitacionActionPerformed

    private void Reserva_De_HabitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Reserva_De_HabitacionActionPerformed
        fromReservaDeHabitacion = new ReservaDeHabitacion();

        jDesktopPane1.add(fromReservaDeHabitacion);
        Dimension desktopSize = jDesktopPane1.getSize();
        Dimension FrameSize = fromReservaDeHabitacion.getSize();
        fromReservaDeHabitacion.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
        fromReservaDeHabitacion.setVisible(true);
        guardaraccion.GuardarEnBitacora("Acceso","2201", Login.usuarioHoteleria);
        logo.setVisible(false);
    }//GEN-LAST:event_Reserva_De_HabitacionActionPerformed

    private void FacturacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FacturacionActionPerformed
        fromFacturacionDeHabitacion = new FacturacionDeHabitacion();
        
        jDesktopPane1.add(fromFacturacionDeHabitacion);
        Dimension desktopSize = jDesktopPane1.getSize();
        Dimension FrameSize = fromFacturacionDeHabitacion.getSize();
        fromFacturacionDeHabitacion.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
        fromFacturacionDeHabitacion.setVisible(true);
        guardaraccion.GuardarEnBitacora("Acceso","2203", Login.usuarioHoteleria);
        logo.setVisible(false);
    }//GEN-LAST:event_FacturacionActionPerformed

    private void Objetos_PerdidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Objetos_PerdidosActionPerformed
        // TODO add your handling code here:
        fromObjetosPerdidos = new ObjetosPerdidos();
        
        jDesktopPane1.add(fromObjetosPerdidos);
        Dimension desktopSize = jDesktopPane1.getSize();
        Dimension FrameSize = fromObjetosPerdidos.getSize();
        fromObjetosPerdidos.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
        fromObjetosPerdidos.setVisible(true);
        guardaraccion.GuardarEnBitacora("Acceso","2204", Login.usuarioHoteleria);
        logo.setVisible(false);
    }//GEN-LAST:event_Objetos_PerdidosActionPerformed

    private void Entrega_Objetos_PerdidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Entrega_Objetos_PerdidosActionPerformed
        // TODO add your handling code here:
        fromObjetosPerdidosEnt = new Entregar_objeto();
        
        jDesktopPane1.add(fromObjetosPerdidosEnt);
        Dimension desktopSize = jDesktopPane1.getSize();
        Dimension FrameSize = fromObjetosPerdidosEnt.getSize();
        fromObjetosPerdidosEnt.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
        fromObjetosPerdidosEnt.setVisible(true);
        guardaraccion.GuardarEnBitacora("Acceso","2205", Login.usuarioHoteleria);
        logo.setVisible(false);
    }//GEN-LAST:event_Entrega_Objetos_PerdidosActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        formBitacoraH = new BitacoraHotelera();
        
        jDesktopPane1.add(formBitacoraH);
        Dimension desktopSize = jDesktopPane1.getSize();
        Dimension FrameSize = formBitacoraH.getSize();
        formBitacoraH.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
        formBitacoraH.setVisible(true);
        logo.setVisible(false);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
    guardaraccion.GuardarEnBitacora("Salir","2000", Login.usuarioHoteleria);
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        //FLATLAF
        try {
            UIManager.setLookAndFeel(new FlatLightLaf());
        } catch (Exception ex) {
            System.out.println(ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new MDIHoteleria().setVisible(true);
                } catch (UnknownHostException ex) {
                    Logger.getLogger(MDIHoteleria.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JMenuItem Entrega_Objetos_Perdidos;
    public static javax.swing.JMenuItem Entregar_Recibir_Habitacion;
    public static javax.swing.JMenuItem Facturacion;
    public static javax.swing.JMenuItem Objetos_Perdidos;
    public static javax.swing.JMenuItem Reserva_De_Habitacion;
    public static javax.swing.JMenu cerrar_sesion;
    public static javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    public static javax.swing.JMenu menu_archivo;
    public static javax.swing.JMenu menu_ayuda;
    public static javax.swing.JMenu menu_catalogos;
    public static javax.swing.JMenu menu_herramientas;
    public static javax.swing.JMenu menu_informes;
    public static javax.swing.JMenu menu_procesos;
    public static javax.swing.JMenuItem mnt_amadellaves;
    public static javax.swing.JMenuItem mnt_formasdepago;
    public static javax.swing.JMenuItem mnt_habitaciones;
    public static javax.swing.JMenuItem mnt_huespedes;
    public static javax.swing.JMenuItem mnt_pisos;
    public static javax.swing.JMenuItem mnt_servicios;
    public static javax.swing.JMenu submenu_mantenimientos;
    public static javax.swing.JMenu submenu_procesos;
    // End of variables declaration//GEN-END:variables
}
