package Hoteleria.vista;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import Hoteleria.datos.HabitacionesDAO;
import Hoteleria.datos.HuespedesDAO;
import Hoteleria.datos.ReservacionDAO;
import Hoteleria.dominio.Habitaciones;
import Hoteleria.dominio.Huespedes;
import Hoteleria.dominio.Reservacion;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.StringTokenizer;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author leone
 */
public class ReservaDeHabitacion extends javax.swing.JInternalFrame {

    DefaultTableModel modelo1;
    String dia_entrada, mes_entrada, año_entrada;
    String dia_salida, mes_salida, año_salida;
    int tot_dias, tot_mes;
    String fechasreservada_inicio[] = new String[3], fechareservada_final[] = new String[3];
    int meses[]={31,28,31,30,31,30,31,31,30,31,30,31};

    /**
     * Creates new form ProcesoReservaDeHS
     */
    public ReservaDeHabitacion() {
        initComponents();
        cargar_habitaciones();
        imprimir_reservaciones();
        fecha_actual();
    }

    public void cargar_habitaciones() {
        HabitacionesDAO personaDAO = new HabitacionesDAO();
        List<Habitaciones> habitaciones = personaDAO.select();
        for (Habitaciones habitacion : habitaciones) {
            c_habitaciones.addItem(String.valueOf(habitacion.getId_Habitaciones()));
        }
    }

    public void imprimir_reservaciones() {
        modelo1 = new DefaultTableModel();   //ASIGNAMOS UN NUEVO DEFAULTABLEMODEL AL OBJETO MODELO1
        modelo1.addColumn("No. Reservación");      //LE AÑADIMOS COLUMNAS AL OBJETO MODELO
        modelo1.addColumn("DPI Cliente");
        modelo1.addColumn("ID Trabajador");      //LE AÑADIMOS COLUMNAS AL OBJETO MODELO
        modelo1.addColumn("ID Habitacion");
        modelo1.addColumn("Fecha de Reserva");
        modelo1.addColumn("Fecha de Entrada");
        modelo1.addColumn("Fecha de Salida");
        tabla1.setModel(modelo1);
        String datos[] = new String[7];
        ReservacionDAO reservaciondao = new ReservacionDAO();
        List<Reservacion> reservacion = reservaciondao.select();
        for (Reservacion reservar : reservacion) {

            datos[0] = reservar.getId_reservacion();
            datos[1] = reservar.getDpi();
            datos[2] = reservar.getId_trabajador();
            datos[3] = reservar.getId_habitacion();
            datos[4] = reservar.getF_reserva();
            datos[5] = reservar.getDesde();
            datos[6] = reservar.getHasta();
            modelo1.addRow(datos);
            tabla1.setModel(modelo1);
        }
    }

    public void limpiar() {
        txt_dpi.setText("");
        txt_nombre_cliente.setText("");
        txt_nit.setText("");
        txt_apellido_cliente.setText("");
        txt_telefono.setText("");
        txt_correo.setText("");
        txt_totalpago.setText("");
        txt_precio.setText("");
    }

    public void fecha_actual() {
        Date date = new Date();
        DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        fecha_actual.setDate(date);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_dpi = new javax.swing.JTextField();
        btnBus = new javax.swing.JButton();
        txt_nombre_cliente = new javax.swing.JTextField();
        txt_apellido_cliente = new javax.swing.JTextField();
        txt_telefono = new javax.swing.JTextField();
        txt_correo = new javax.swing.JTextField();
        fecha_actual = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        fecha_entrada = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        fecha_salida = new com.toedter.calendar.JDateChooser();
        jButton2 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        txt_precio = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        btnIns = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        txt_totalpago = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txt_nit = new javax.swing.JTextField();
        c_habitaciones = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla1 = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Reservación de Habitación o Salón");
        setVisible(true);

        jPanel1.setForeground(new java.awt.Color(240, 240, 240));

        jLabel1.setText("Fecha:");

        jLabel2.setText("Nombre:");

        jLabel3.setText("Apellido:");

        jLabel4.setText("Telefono:");

        jLabel5.setText("Correo:");

        jLabel6.setText("No. de DPI:");

        txt_dpi.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        btnBus.setText("CARGAR");
        btnBus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBusActionPerformed(evt);
            }
        });

        txt_nombre_cliente.setEditable(false);
        txt_nombre_cliente.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txt_apellido_cliente.setEditable(false);
        txt_apellido_cliente.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txt_telefono.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_telefono.setEnabled(false);

        txt_correo.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        fecha_actual.setDateFormatString("dd/MM/yyyy");
        fecha_actual.setEnabled(false);

        jLabel7.setText("Fecha de Entrada:");

        fecha_entrada.setDateFormatString("dd/MM/yyyy");

        jLabel8.setText("Fecha de Salida:");

        fecha_salida.setDateFormatString("dd/MM/yyyy");

        jButton2.setText("VERIFICAR DISPONIBILIDAD");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel11.setText("Precio por noche:");

        txt_precio.setEditable(false);
        txt_precio.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jButton5.setText("CANCELAR");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        btnIns.setText("GUARDAR");

        jButton7.setText("AYUDA");

        jLabel13.setText("Total a Pagar:");

        txt_totalpago.setEditable(false);
        txt_totalpago.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel14.setText("NIT:");

        txt_nit.setEditable(false);
        txt_nit.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel15.setText("ID habitación o salón:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txt_dpi, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnBus))
                                    .addComponent(txt_nombre_cliente)
                                    .addComponent(txt_apellido_cliente)
                                    .addComponent(txt_telefono)
                                    .addComponent(txt_correo)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel13))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txt_totalpago, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(fecha_entrada, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                                    .addComponent(fecha_salida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel14))
                                .addGap(26, 26, 26)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fecha_actual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txt_nit)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(c_habitaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_precio))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton7)
                        .addGap(18, 18, 18)
                        .addComponent(btnIns)
                        .addGap(18, 18, 18)
                        .addComponent(jButton5)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(fecha_actual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel6)
                        .addComponent(txt_dpi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnBus)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_nombre_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(txt_nit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_apellido_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_correo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(fecha_entrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(c_habitaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel15)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(fecha_salida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8))
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txt_totalpago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(txt_precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(btnIns)
                    .addComponent(jButton7))
                .addContainerGap())
        );

        tabla1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tabla1.setGridColor(new java.awt.Color(204, 204, 255));
        jScrollPane1.setViewportView(tabla1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 752, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 543, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBusActionPerformed
        HuespedesDAO huespedesdao = new HuespedesDAO();
        Huespedes buscarmetodo = new Huespedes();

        buscarmetodo.setCodigo(txt_dpi.getText());
        buscarmetodo = huespedesdao.query(buscarmetodo);
        txt_nombre_cliente.setText(buscarmetodo.getNombre());
        txt_apellido_cliente.setText(buscarmetodo.getApellido());
        txt_nit.setText(buscarmetodo.getNit());
        txt_telefono.setText(buscarmetodo.getTelefono());

    }//GEN-LAST:event_btnBusActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int c = 0, sd_entrada = 0, sm_entrada = 0, sd_salida = 0, sm_salida = 0, d1, m1, d2, m2, cantidad_dias = 0, totalpago = 0,auxsm;
        String newparra;
        String fechaentrada = new SimpleDateFormat("dd/MM/yyyy").format(fecha_entrada.getDate());
        String fechasalida = new SimpleDateFormat("dd/MM/yyyy").format(fecha_salida.getDate());
        dia_entrada = fechaentrada.split("/")[0];
        mes_entrada = fechaentrada.split("/")[1];
        año_entrada = fechaentrada.split("/")[2];
        dia_salida = fechasalida.split("/")[0];
        mes_salida = fechasalida.split("/")[1];
        año_salida = fechasalida.split("/")[2];
        sd_entrada = Integer.parseInt(dia_entrada);
        sm_entrada = Integer.parseInt(mes_entrada);
        sd_salida = Integer.parseInt(dia_salida);
        sm_salida = Integer.parseInt(mes_salida);

        boolean reservado = false, ciclo = false;

        HabitacionesDAO habitacionesdao = new HabitacionesDAO();
        Habitaciones consultarhabitacion = new Habitaciones();
        consultarhabitacion.setId_Habitaciones(Integer.parseInt(c_habitaciones.getSelectedItem().toString()));
        consultarhabitacion = habitacionesdao.query(consultarhabitacion);

        ReservacionDAO reservaciondao = new ReservacionDAO();
        List<Reservacion> reservacion = reservaciondao.select();
        for (Reservacion reservar : reservacion) {
            if (c_habitaciones.getSelectedItem().toString().equals(reservar.getId_habitacion())) {
                StringTokenizer st = new StringTokenizer(reservar.getDesde(), "-");
                int a = 0;
                newparra = "";
                while (st.hasMoreTokens()) {
                    newparra = st.nextToken();
                    fechasreservada_inicio[a] = newparra;
                    a++;
                }
                StringTokenizer st2 = new StringTokenizer(reservar.getHasta(), "-");
                int b = 0;
                while (st2.hasMoreTokens()) {
                    newparra = st2.nextToken();
                    fechareservada_final[b] = newparra;
                    b++;
                }

                d1 = Integer.parseInt(fechasreservada_inicio[2]);
                m1 = Integer.parseInt(fechasreservada_inicio[1]);
                d2 = Integer.parseInt(fechareservada_final[2]);
                m2 = Integer.parseInt(fechareservada_final[1]);

                //SE CAPTURAN EL DIA Y MES DE LAS FECHAS SOLICITADAS
                if (sm_entrada == sm_salida) {
                    for (int i = sd_entrada; i <= sd_salida; i++) {
                        if (i == d1 || i == d2) {
                            reservado = true;
                        }
                    }
                } else if (sm_salida > sm_entrada) {
                    for (int i = sm_entrada; i < sm_salida; i++) {
                        if (ciclo = false) {
                            for (int j = sd_entrada; j <= 31; j++) {
                                if (sm_entrada == m1) {
                                    reservado = true;
                                }
                            }
                        } else if (i >= m1 && i < m2) {
                            reservado = true;
                        } else if (i == m2) {
                            for (int j = 0; j <= d2; j++) {
                                if (j == d2) {
                                    reservado = true;
                                }
                            }
                        }
                        ciclo = true;
                    }
                }

            }
        }
        cantidad_dias=0;
        if (Integer.parseInt(año_salida)==Integer.parseInt(año_entrada)) {
            
            if (sm_entrada == sm_salida) {
                    if (sd_entrada<sd_salida) {
                        for (int i = sd_entrada; i < sd_salida; i++) {
                        cantidad_dias++;
                    }
                }else {
                        JOptionPane.showMessageDialog(null, "Fecha de reservación invalida, no puede reservar dias ya cumplidos");
                    }
            }
            
            if (sm_salida > sm_entrada) {
            }
                for (int i = sm_entrada; i < sm_salida; i++) {
                    for (int j = 0; j < meses[sm_salida]; j++) {
                        cantidad_dias++;
                    }
                }
                for (int i = 0; i < sd_salida; i++) {
                    cantidad_dias++;
                }
                System.out.println(cantidad_dias++);
            
        }else if(Integer.parseInt(año_salida)<Integer.parseInt(año_entrada)){
            
            JOptionPane.showMessageDialog(null, "Fechas de reservación invalida, no puede reservar dias ya cumplidos");
            btnIns.setEnabled(false);reservado=true;
            
        }else if(Integer.parseInt(año_salida)>Integer.parseInt(año_entrada)){
            
            /*if (sm_salida > sm_entrada) {
                for (int i = sd_entrada; i < 31; i++) {
                    cantidad_dias++;
                }
                for (int i = 0; i < sd_salida; i++) {
                    cantidad_dias++;
                }
            }*/
            
            
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        limpiar();
    }//GEN-LAST:event_jButton5ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBus;
    private javax.swing.JButton btnIns;
    private javax.swing.JComboBox<String> c_habitaciones;
    private com.toedter.calendar.JDateChooser fecha_actual;
    private com.toedter.calendar.JDateChooser fecha_entrada;
    private com.toedter.calendar.JDateChooser fecha_salida;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla1;
    private javax.swing.JTextField txt_apellido_cliente;
    private javax.swing.JTextField txt_correo;
    private javax.swing.JTextField txt_dpi;
    private javax.swing.JTextField txt_nit;
    private javax.swing.JTextField txt_nombre_cliente;
    private javax.swing.JTextField txt_precio;
    private javax.swing.JTextField txt_telefono;
    private javax.swing.JTextField txt_totalpago;
    // End of variables declaration//GEN-END:variables
}
