/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Comercial.vista;

import Comercial.datos.InventarioDAO;
import Comercial.dominio.Inventario;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Diana
 */
public class Mantenimiento_Inventario extends javax.swing.JFrame {

    DefaultTableModel modelo1;

    /**
     * Creates new form Mantenimiento_Inventario
     */
    public void llenadoDeTablas() {
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("ARTICULO");
        modelo.addColumn("NOMBRE DE ARTICULO");
        modelo.addColumn("CARACTERISTICAS");
        modelo.addColumn("REFERENCIA FABRICANTE");
        modelo.addColumn("PRECIO DE COMPRA");
        modelo.addColumn("MARGEN");
        modelo.addColumn("DECUENTO DE COMPRA");
        modelo.addColumn("DESCUENTO DE VENTA");
        modelo.addColumn("CANTIDAD DE ARTICULO");
        modelo.addColumn("CADUCIDAD DE ARTICULO");
        InventarioDAO inventarioDAO = new InventarioDAO();
        List<Inventario> inventarios = inventarioDAO.select();
        tablaInventario.setModel(modelo);
        String[] dato = new String[10];
        for (int i = 0; i < inventarios.size(); i++) {
            dato[0] = Integer.toString(inventarios.get(i).getId_Inventario());
            dato[1] = inventarios.get(i).getNombre_Articulo();
            dato[2] = inventarios.get(i).getCaracteristica_Articulo();
            dato[3] = inventarios.get(i).getReferecia_fabricante();
            dato[4] = inventarios.get(i).getPrecio_Compra();
            dato[5] = inventarios.get(i).getMargen();
            dato[6] = inventarios.get(i).getDescuento_Compra();
            dato[7] = inventarios.get(i).getDescuento_Venta();
            dato[8] = inventarios.get(i).getCantidad_Articulo();
            dato[9] = inventarios.get(i).getCaducidad_Articulo();

//System.out.println("vendedor:" + vendedores);
            modelo.addRow(dato);
        }
    }

    public void buscarArticulo() {
        Inventario inventarioAConsultar = new Inventario();
        InventarioDAO inventarioDAO = new InventarioDAO();
        inventarioAConsultar.setId_Inventario(Integer.parseInt(txtArticulo.getText()));
        inventarioAConsultar = inventarioDAO.query(inventarioAConsultar);
        txtNombreArticulo.setText(inventarioAConsultar.getNombre_Articulo());
        txtCaracteristica.setText(inventarioAConsultar.getCaracteristica_Articulo());
        txtReferenciaFabricante.setText(inventarioAConsultar.getReferecia_fabricante());
        txtPrecioCompra.setText(inventarioAConsultar.getPrecio_Compra());
        txtMargen.setText(inventarioAConsultar.getMargen());

        txtDescuentoCompra.setText(inventarioAConsultar.getDescuento_Compra());
        txtDescuentoVenta.setText(inventarioAConsultar.getDescuento_Venta());
        txtCantidadArticulo.setText(inventarioAConsultar.getCantidad_Articulo());
        txtCaducidadArticulo.setText(inventarioAConsultar.getCaducidad_Articulo());

    }

    public Mantenimiento_Inventario() {
        initComponents();
//            setLocationRelativeTo(null); 
//        setSize(400, 200);
//        setDefaultCloseOperation(EXIT_ON_CLOSE)

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnAgregar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnAyuda = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtArticulo = new javax.swing.JTextField();
        txtNombreArticulo = new javax.swing.JTextField();
        txtCaracteristica = new javax.swing.JTextField();
        txtReferenciaFabricante = new javax.swing.JTextField();
        txtMargen = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtPrecioCompra = new javax.swing.JTextField();
        txtDescuentoCompra = new javax.swing.JTextField();
        txtDescuentoVenta = new javax.swing.JTextField();
        txtCantidadArticulo = new javax.swing.JTextField();
        txtCaducidadArticulo = new javax.swing.JTextField();
        btnLimpiar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaInventario = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MANTENIMIENTO INVENTARIO");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos"));

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnAyuda.setText("Ayuda");
        btnAyuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAyudaActionPerformed(evt);
            }
        });

        jLabel1.setText("Articulo");

        jLabel2.setText("Nombre Articulo");

        jLabel3.setText("Caracteristica Articulo");

        jLabel4.setText("Referencia Fabricante");

        jLabel5.setText("Margen");

        jLabel6.setText("Precio de Compra");

        jLabel7.setText("Descuento Compra");

        jLabel8.setText("Descuento Venta");

        jLabel9.setText("Cantidad de Articulo");

        jLabel10.setText("Caducidad de Articulo");

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(406, 406, 406)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDescuentoCompra)
                            .addComponent(txtPrecioCompra))
                        .addGap(68, 68, 68))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtReferenciaFabricante)
                                    .addComponent(txtMargen, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(116, 116, 116)
                                        .addComponent(jLabel1)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtArticulo))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGap(47, 47, 47)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel3)
                                                .addGap(18, 18, 18)
                                                .addComponent(txtCaracteristica, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addGap(18, 18, 18)
                                                .addComponent(txtNombreArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(74, 74, 74)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtCaducidadArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtCantidadArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtDescuentoVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(124, 124, 124)
                                .addComponent(btnAgregar)
                                .addGap(18, 18, 18)
                                .addComponent(btnBuscar)
                                .addGap(18, 18, 18)
                                .addComponent(btnModificar)
                                .addGap(18, 18, 18)
                                .addComponent(btnEliminar)
                                .addGap(18, 18, 18)
                                .addComponent(btnLimpiar)
                                .addGap(18, 18, 18)
                                .addComponent(btnAyuda)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(50, 50, 50))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAgregar)
                            .addComponent(btnBuscar)
                            .addComponent(btnModificar)
                            .addComponent(btnEliminar)
                            .addComponent(btnLimpiar)
                            .addComponent(btnAyuda))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(txtPrecioCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(txtNombreArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDescuentoCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtCaracteristica, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtDescuentoVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtCantidadArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtCaducidadArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtReferenciaFabricante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMargen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Detalle"));

        tablaInventario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tablaInventario);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 781, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
//        Inventario inventarioInsertar = new Inventario();
//        InventarioDAO inventarioDAO = new InventarioDAO();
//
//        if (txtArticulo.getText().length() != 0 && txtNombreArticulo.getText().length() != 0
//                && txtCaracteristica.getText().length() != 0
//                && txtReferenciaFabricante.getText().length() != 0 && txtMargen.getText().length() != 0
//                && txtPrecioCompra.getText().length() != 0 && txtDescuentoCompra.getText().length() != 0
//                && txtDescuentoVenta.getText().length() != 0 && txtCantidadArticulo.getText().length() != 0
//                && txtCaducidadArticulo.getText().length() != 0) {
//            {
//                inventarioInsertar.setId_Inventario(Integer.parseInt(txtArticulo.getText()));
//                inventarioInsertar.setNombre_Articulo(txtNombreArticulo.getText());
//                inventarioInsertar.setCaracteristica_Articulo(txtCaracteristica.getText());
//                inventarioInsertar.setReferecia_fabricante(txtReferenciaFabricante.getText());
//                inventarioInsertar.setMargen(txtMargen.getText());
//                inventarioInsertar.setPrecio_Compra(txtPrecioCompra.getText());
//
//                inventarioInsertar.setDescuento_Compra(txtDescuentoCompra.getText());
//                inventarioInsertar.setDescuento_Venta(txtDescuentoVenta.getText());
//                inventarioInsertar.setCantidad_Articulo(txtCantidadArticulo.getText());
//                inventarioInsertar.setCaducidad_Articulo(txtCaducidadArticulo.getText());
//
//            }
//
//        } else {
//            JOptionPane.showMessageDialog(null, "Todos los campos tienen que estar llenos");
//        }

        InventarioDAO inventariDAO = new InventarioDAO();
        Inventario inventarioAInsertar = new Inventario();
        // inventarioAInsertar.setNombreVendedor(txtArticulo.getText());
        inventarioAInsertar.setNombre_Articulo(txtNombreArticulo.getText());
        inventarioAInsertar.setCaracteristica_Articulo(txtCaracteristica.getText());
        inventarioAInsertar.setReferecia_fabricante(txtReferenciaFabricante.getText());
        inventarioAInsertar.setPrecio_Compra(txtPrecioCompra.getText());
        inventarioAInsertar.setMargen(txtMargen.getText());
        inventarioAInsertar.setDescuento_Compra(txtDescuentoCompra.getText());
        inventarioAInsertar.setDescuento_Venta(txtDescuentoVenta.getText());
        inventarioAInsertar.setCantidad_Articulo(txtCantidadArticulo.getText());
        inventarioAInsertar.setCaducidad_Articulo(txtCaducidadArticulo.getText());

        inventariDAO.insert(inventarioAInsertar);
        llenadoDeTablas();


    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
//        Inventario inventarioModificar = new Inventario();
//        InventarioDAO inventarioDAO = new InventarioDAO();
//
//        inventarioModificar.setId_Inventario(Integer.parseInt(txtArticulo.getText()));
//        inventarioModificar.setNombre_Articulo(txtNombreArticulo.getText());
//        inventarioModificar.setCaracteristica_Articulo(txtCaracteristica.getText());
//        inventarioModificar.setReferecia_fabricante(txtReferenciaFabricante.getText());
//        inventarioModificar.setMargen(txtMargen.getText());
//        inventarioModificar.setPrecio_Compra(txtPrecioCompra.getText());
//
//        inventarioModificar.setDescuento_Compra(txtDescuentoCompra.getText());
//        inventarioModificar.setDescuento_Venta(txtDescuentoVenta.getText());
//        inventarioModificar.setCantidad_Articulo(txtCantidadArticulo.getText());
//        inventarioModificar.setCaducidad_Articulo(txtCaducidadArticulo.getText());
//
//        inventarioDAO.update(inventarioModificar);
//        JOptionPane.showMessageDialog(null, "Modificación Exitosa.");
//
//        tabla();
//        limpiar();

        InventarioDAO inventarioDAO = new InventarioDAO();
        Inventario inventarioAActualizar = new Inventario();
        inventarioAActualizar.setId_Inventario(Integer.parseInt(txtArticulo.getText()));
        inventarioAActualizar.setNombre_Articulo(txtNombreArticulo.getText());
        inventarioAActualizar.setCaracteristica_Articulo(txtCaracteristica.getText());
        inventarioAActualizar.setReferecia_fabricante(txtReferenciaFabricante.getText());
        inventarioAActualizar.setPrecio_Compra(txtPrecioCompra.getText());
        inventarioAActualizar.setMargen(txtMargen.getText());
        inventarioAActualizar.setDescuento_Compra(txtDescuentoCompra.getText());
        inventarioAActualizar.setDescuento_Venta(txtDescuentoVenta.getText());
        inventarioAActualizar.setCantidad_Articulo(txtCantidadArticulo.getText());
        inventarioAActualizar.setCaducidad_Articulo(txtCaducidadArticulo.getText());

        inventarioDAO.update(inventarioAActualizar);
        llenadoDeTablas();

    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
//        Inventario inventarioEliminar = new Inventario();
//        InventarioDAO inventarioDAO = new InventarioDAO();
//
//        inventarioEliminar.setId_Inventario(Integer.parseInt(txtArticulo.getText()));
//        inventarioDAO.delete(inventarioEliminar);
//        JOptionPane.showMessageDialog(null, "Registro Eliminado.");
//        tabla();
//        limpiar();
        InventarioDAO inventarioDAO = new InventarioDAO();
        Inventario inventarioAEliminar = new Inventario();
        inventarioAEliminar.setId_Inventario(Integer.parseInt(txtArticulo.getText()));
        inventarioDAO.delete(inventarioAEliminar);
        llenadoDeTablas();

    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
//        Inventario inventarioBuscar = new Inventario();
//        InventarioDAO inventarioDAO = new InventarioDAO();
//        inventarioBuscar.setId_Inventario(Integer.parseInt(txtArticulo.getText()));
//
//        inventarioBuscar = inventarioDAO.query(inventarioBuscar);
//
//        txtNombreArticulo.setText(String.valueOf(inventarioBuscar.getNombre_Articulo()));
//        txtCaracteristica.setText(String.valueOf(inventarioBuscar.getCaracteristica_Articulo()));
//        txtReferenciaFabricante.setText(String.valueOf(inventarioBuscar.getReferecia_fabricante()));
//        txtMargen.setText(String.valueOf(inventarioBuscar.getMargen()));
//        txtPrecioCompra.setText(String.valueOf(inventarioBuscar.getPrecio_Compra()));
//        txtDescuentoCompra.setText(String.valueOf(inventarioBuscar.getDescuento_Compra()));
//        txtDescuentoVenta.setText(String.valueOf(inventarioBuscar.getDescuento_Venta()));
//        txtCantidadArticulo.setText(String.valueOf(inventarioBuscar.getCantidad_Articulo()));
//        txtCaducidadArticulo.setText(String.valueOf(inventarioBuscar.getCaducidad_Articulo()));
        buscarArticulo();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:

        txtArticulo.setText("");
        txtNombreArticulo.setText("");
        txtCaracteristica.setText("");
        txtReferenciaFabricante.setText("");
        txtPrecioCompra.setText("");
        txtMargen.setText("");

        txtDescuentoCompra.setText("");
        txtDescuentoVenta.setText("");
        txtCantidadArticulo.setText("");
        txtCaducidadArticulo.setText("");
        btnAgregar.setEnabled(true);
        btnModificar.setEnabled(true);
        btnEliminar.setEnabled(true);
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnAyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAyudaActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_btnAyudaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mantenimiento_Inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mantenimiento_Inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mantenimiento_Inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mantenimiento_Inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mantenimiento_Inventario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnAyuda;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaInventario;
    private javax.swing.JTextField txtArticulo;
    private javax.swing.JTextField txtCaducidadArticulo;
    private javax.swing.JTextField txtCantidadArticulo;
    private javax.swing.JTextField txtCaracteristica;
    private javax.swing.JTextField txtDescuentoCompra;
    private javax.swing.JTextField txtDescuentoVenta;
    private javax.swing.JTextField txtMargen;
    private javax.swing.JTextField txtNombreArticulo;
    private javax.swing.JTextField txtPrecioCompra;
    private javax.swing.JTextField txtReferenciaFabricante;
    // End of variables declaration//GEN-END:variables
}
