/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Comercial.vista;

import Comercial.datos.ProcesoProductoDAO;
import Comercial.dominio.ProcesoProducto;
import java.awt.HeadlessException;
import java.io.File;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import seguridad.vista.GenerarPermisos;
import seguridad.vista.MDI_Components;

/**
 *
 * @author Diana
 */
public class Proceso_Producto extends javax.swing.JInternalFrame {

    /**
     * Creates new form Proceso_Producto
     */
    public void llenadoDeTablas() {
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("ID Proveedor");
        modelo.addColumn("Producto");
        modelo.addColumn("Bodega");
        modelo.addColumn("Existencias");

        ProcesoProductoDAO procesoproductoDAO = new ProcesoProductoDAO();

        List<ProcesoProducto> procesoproducto = procesoproductoDAO.select();
        TablaProducto.setModel(modelo);
        String[] dato = new String[5];
        for (int i = 0; i < procesoproducto.size(); i++) {
            dato[0] = Integer.toString(procesoproducto.get(i).getPK_id_procesoproducto());
            dato[1] = procesoproducto.get(i).getNombre_producto();
            dato[2] = procesoproducto.get(i).getNombre_bodega();
            dato[3] = procesoproducto.get(i).getExistencias_producto();

            //System.out.println("vendedor:" + vendedores);
            modelo.addRow(dato);
        }
    }

    public void buscar() {
        ProcesoProducto productoAConsultar = new ProcesoProducto();
        ProcesoProductoDAO procesoproductoDAO = new ProcesoProductoDAO();
        productoAConsultar.setPK_id_procesoproducto(Integer.parseInt(txtIDprocesoproducto.getText()));
        productoAConsultar = procesoproductoDAO.query(productoAConsultar);
        txtNombreProducto.setText(productoAConsultar.getNombre_producto());
        txtnombrebodega.setText(productoAConsultar.getNombre_bodega());
        txtExistenciasProducto.setText(productoAConsultar.getExistencias_producto());

    }

    public void limpiar() {
        txtIDprocesoproducto.setText("");
        txtNombreProducto.setText("");
        txtnombrebodega.setText("");
        txtExistenciasProducto.setText("");

    }

    public Proceso_Producto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNombreProducto = new javax.swing.JTextField();
        txtnombrebodega = new javax.swing.JTextField();
        txtExistenciasProducto = new javax.swing.JTextField();
        btnValidar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtIDprocesoproducto = new javax.swing.JTextField();
        btnAyuda = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaProducto = new javax.swing.JTable();

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("PROCESO PRODUCTOS");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Detalle"));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Producto");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Bodega");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Existencias");

        btnValidar.setText("Validar");
        btnValidar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValidarActionPerformed(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("ID");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNombreProducto, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                    .addComponent(txtnombrebodega)
                    .addComponent(txtExistenciasProducto)
                    .addComponent(txtIDprocesoproducto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 133, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnValidar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtIDprocesoproducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtNombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtnombrebodega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtExistenciasProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 21, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnValidar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnGuardar)))
                .addContainerGap())
        );

        btnAyuda.setText("Ayuda");
        btnAyuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAyudaActionPerformed(evt);
            }
        });

        TablaProducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(TablaProducto);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 471, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(167, 167, 167)
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAyuda))))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAyuda)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnValidarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValidarActionPerformed
        // TODO add your handling code here:}buscar();
        GenerarPermisos permisos = new GenerarPermisos();
        MDI_Components mdi_Components = new MDI_Components();

        if (txtnombrebodega.getText().trim().isEmpty() || txtExistenciasProducto.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "NO PUEDEN HABER CAMPOS VACIOS", "ERROR", JOptionPane.ERROR_MESSAGE);
        } else {
            try {

                //viene de Uusuario y UsuarioDAO ...
                ProcesoProducto usuarioAConsultar = new ProcesoProducto();
                ProcesoProductoDAO procesoproductoDAO = new ProcesoProductoDAO();
                usuarioAConsultar.setNombre_bodega((txtnombrebodega.getText()));

                //                BitacoraDao BitacoraDAO = new BitacoraDao();
                //
                //                Bitacora Insertar = new Bitacora();
                //                Insertar.setId_Usuario("Proceso_Producto");
                //                Insertar.setAccion("Insertar");
                //                Insertar.setCodigoAplicacion("000");
                //                Insertar.setModulo("3009");
                //
                //                try {
                //                    BitacoraDAO.insert(Insertar);
                //                } catch (UnknownHostException ex) {
                //                    Logger.getLogger(Aplicacion_Perfil.class.getName()).log(Level.SEVERE, null, ex);
                //                }
                System.out.println(usuarioAConsultar.toString());
                // Recuperación de información a través de otro objeto
                usuarioAConsultar = procesoproductoDAO.query(usuarioAConsultar);

                //                System.out.println("regresa " + usuarioAConsultar.toString());
                //
                //                System.out.println("regresa contraseña " + txtContraseña.getText());
                //
                //                System.out.println("regresa objeto contraseña " + usuarioAConsultar.getPassword_usuario());
                //
                //                System.out.println("regresa usuario " + txtUsuario.getText());
                //
                //                System.out.println("regresa objeto usuario " + usuarioAConsultar.getId_usuario());
                //**********************************************************************************************************************************************************************
                if (txtnombrebodega.getText().equals(usuarioAConsultar.getNombre_bodega()) && txtExistenciasProducto.getText().equals(usuarioAConsultar.getExistencias_producto())) {
                    //  if (txtUsuario.getText().equals(Integer.toString(usuarioAConsultar.getId_usuario()))) {
                    // if (txtContraseña.getText().equals(usuarioAConsultar.getPassword_usuario())){
                    JOptionPane.showMessageDialog(null, "Bienvenido\n", "Mensaje de bienvenida", JOptionPane.INFORMATION_MESSAGE);

                    //buscar nombre de producto
                    //variable local
                    //if = a lo que tengo en producto y si es asi que lo elimine JOptionPane
                    //si no que lo guarde normal
                }
            } catch (HeadlessException e) {
                JOptionPane.showMessageDialog(this, "ERROR AL ENCONTRAR USUARIO O CONTRASEÑA", "ERROR", JOptionPane.ERROR_MESSAGE);
                txtnombrebodega.setText("");
                txtExistenciasProducto.setText("");
            }
        }
    }//GEN-LAST:event_btnValidarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        GenerarPermisos permisos = new GenerarPermisos();
        MDI_Components mdi_Components = new MDI_Components();

        String id = "0";
        MantenimientoProductos manteminetoProductosDAO = new MantenimientoProductos();

        ProcesoProductoDAO procesoproductoDAO = new ProcesoProductoDAO();
        ProcesoProducto productoAInsertar = new ProcesoProducto();

        productoAInsertar.setPK_id_procesoproducto((int) Integer.parseInt(txtIDprocesoproducto.getText()));
        productoAInsertar.setNombre_producto(txtNombreProducto.getText());
        productoAInsertar.setNombre_bodega(txtnombrebodega.getText());
        productoAInsertar.setExistencias_producto(txtExistenciasProducto.getText());

        procesoproductoDAO.insert(productoAInsertar);

        //BITACORA
        //        BitacoraDao BitacoraDAO = new BitacoraDao();
        //        Bitacora Insertar = new Bitacora();
        //        Insertar.setId_Usuario("MantenimientoProductos");
        //        Insertar.setAccion("Insertar");
        //        Insertar.setCodigoAplicacion("3000");
        //        Insertar.setId_Usuario(Login.usuarioComercial);
        //
        //        try {
        //            BitacoraDAO.insert(Insertar);
        //        } catch (UnknownHostException ex) {
        //            Logger.getLogger(Aplicacion_Perfil.class.getName()).log(Level.SEVERE, null, ex);
        //        }
        llenadoDeTablas();
        limpiar();

    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnAyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAyudaActionPerformed
        // TODO add your handling code here:
        try {
            if ((new File("src\\main\\java\\Comercial\\reportes\\AyudaMantenimientoProducto.chm")).exists()) {
                Process p = Runtime
                        .getRuntime()
                        .exec("rundll32 url.dll,FileProtocolHandler src\\main\\java\\Comercial\\reportes\\AyudaMantenimientoProducto.chm");
                p.waitFor();
            } else {
                JOptionPane.showMessageDialog(null, "La ayuda no Fue encontrada");
            }
            //System.out.println("Correcto");
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnAyudaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaProducto;
    private javax.swing.JButton btnAyuda;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnValidar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtExistenciasProducto;
    private javax.swing.JTextField txtIDprocesoproducto;
    private javax.swing.JTextField txtNombreProducto;
    private javax.swing.JTextField txtnombrebodega;
    // End of variables declaration//GEN-END:variables
}
