/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import modelo.Conexion;
import modelo.Hash;
import modelo.LOGINDM;
import modelo.LoginDAO;
import modelo.SqlUsuarios;
import modelo.Usuarios;



/**
 *
 * @author Diana
 */
public class CambioClave extends javax.swing.JFrame {
   
    static Connection con = null ;
//    private static String ced1;
//        
//    int x,y;
//    private String pass;
//    private String Usuarios;
    /**
     * Creates new form CambioClave
     */
    public CambioClave() {
        initComponents();
//     setLocalRelativeTo(null);
    //   cod.requestFocus();
    }

    
    //*****************************************************************************************************
//             void Cambio_Contraseña() throws SQLException
//             {
//              String clavevacia=jPasswordNew.getText();
//              String confavacia=jpassconfirmclave.getText();
//              
//              if (("".equals(clavevacia)|| ("".equals(confavacia))))
//              {
//                  JOptionPane.showMessageDialog(null, "No pueden haber campos vacios");
//                  jPasswordNew.requestFocus();
//                  
//              }else{
//                  if(jPasswordNew.getText().equals(jpassconfirmclave.getText()))
//                  {
//                      int resp = JOptionPane.showConfirmDialog(null, "¿Deseas Guardar la Contraseña?");
//                      
//                      if (resp==0)
//                      {
//                          String cont = jPasswordNew.getText();
//                          
//                          try{
//                              //          update actualizar  set colocar     where donde
//                              String sql = "UPDATE usuarios SET password=?  WHERE id=? ";
//                              PreparedStatement pst = con.prepareCall(sql);
//  
//                              pst.setString(1, cont);
//                              pst.setString(2, CambioClave.ced1);
//                              
//                              int a = pst.executeUpdate();
//                              JOptionPane.showMessageDialog(null, "Contraseña nueva guardada");    
//                              
//                              }catch(Exception e){ 
//                              }
//
//                                  dispose ();
//                              login a = new login();
//                              a.setVisible(true);
//                       
//                                }} else {
//                                JOptionPane.showMessageDialog(null, "Las contraseñas no coinciden");                            
//                                 } 
//              } 
//}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cod = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnLogin.setText("Aceptar");
        btnLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLoginMouseClicked(evt);
            }
        });
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Escriba su nueva contraseña");

        jLabel2.setText("Nueva Contraseña");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(btnLogin))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cod, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(btnLogin)
                .addGap(48, 48, 48))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   
    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
    
        
                  LoginDAO modulosDAO = new LoginDAO();
                LOGINDM moduloActualizar = new LOGINDM();
                moduloActualizar.setCodigo(cod.getText());
           //     moduloActualizar.setContra(contra.getText());
                modulosDAO.update(moduloActualizar);
 
        //***********************************************************************************************************
        
        
        
      //                   try {
//            String ID = jPasswordNew.getText().trim();
//
//            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/usuarios", "root", "");
//            PreparedStatement pst = cn.prepareStatement("update usuarios set password = ? where usaurio = " + ID);
//
//            pst.setString(1, jPasswordNew.getText().trim());
//           // pst.setString(2, jpassconfirmclave.getText().trim()); 
//            Label_status.setText("Modificación exitosa.");
//             dispose ();
//             login a = new login();
//             a.setVisible(true);
//        } catch (Exception e) {
//            
//        }
//                SqlUsuarios modSql = new SqlUsuarios();
//                Usuarios mod = new Usuarios();
//              //   String  ced_trans = jPasswordNew.getText();
//   
//              String clavevacia=jPasswordNew.getText();
//              String confavacia=jpassconfirmclave.getText();
//              
//              if (("".equals(clavevacia)|| ("".equals(confavacia)))){
//            
//            String nuevoPass = Hash.sha1(pass);
//            
//            mod.setUsuario(jPasswordNew.getText());
//            mod.setUsuario(jpassconfirmclave.getText());
//            mod.setPassword(nuevoPass);
//            
//            if (modSql.login(mod)) {
//                login.frmLog = null;
//                this.dispose();
//                
//               login  frmentrada = new login();
//                frmentrada.setVisible(true);
//                
//            } else {
//                JOptionPane.showMessageDialog(null, "Datos incorrectos");
//                limpiar();
//            }
//        } else {
//            JOptionPane.showMessageDialog(null, "Debe ingresar sus datos");
//        }

    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLoginMouseClicked

   private void limpiar() {
        cod.setText("");
        //jpassconfirmclave.setText("");

    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CambioClave.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CambioClave.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CambioClave.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CambioClave.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CambioClave().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JPasswordField cod;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables

   

  }