/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Diana
 */
public class Recuperacio extends javax.swing.JFrame {
    public static String resp="";
        public static String ced1="";
        int x,y;
        static Connection con=null;
    /**
     * Creates new form Recuperacio
     */
    public Recuperacio() {
        initComponents();
        txtid.requestFocus();
        
    }
    //***************************************************************************************************************

//CONFIRMAR USUARIO    
    
    void Confirmar_Usuario(){
          
        String ced_tra = txtid.getText();
       
        try{
            if ("".equals((ced_tra)))
            {
                    JOptionPane.showMessageDialog(null, "No pueden haber campos vacios");
                    txtid.requestFocus();       
            }else{
                   // con =Connection.Conexion.Conexion;
                    
            Connection cn= DriverManager.getConnection("jdbc:mysql://localhost/Usuarios","root","");   
//                String sql= "SELECT * FROM usuarios WHERE usuario='" + txtusuario.getText() + "'";
////                                     Statement st=con.createStatement();
            PreparedStatement pst = cn.prepareStatement("select * from usuarios where usuario = ?");
            pst.setString(1, txtid.getText().trim());
            ResultSet rs = pst.executeQuery();

        //    PreparedStatement pst = cn.prepareStatement("select * from usuarios where usuario = ?");
         //   pst.setString(1, txtusuario.getText().trim());

  //          ResultSet rs = pst.executeQuery();

              //busca
             //  ResultSet rs = st.executeQuery(sql);
                String preg="";
                String cedu="";
                
                if (rs.next()){
                    //busca
                    cedu=rs.getString("usuario");
                    preg=rs.getString("pregunta");
                 //   Recuperacio.resp= rs.getString("respuesta");
                     
                   
                } else {
                    JOptionPane.showConfirmDialog(null, "Nombre de Usuario Incorrecto");
                    txtid.setText("");
                    txtid.requestFocus();
                }
 //**********************************************************************************************************
                //CONFIGURACION DE PREGUNTA EN EL PANEL 
//                Recuperacio.ced1=cedu;
//                jpanel_pregun_pane.removeAll();
//                jpanel_pregun_pane.updateUI();
//                jpanel_pregun_pane.repaint();                
//                this.validate(); 
//                lblpregunta.setText(preg);
//                jpanel_pregun_pane.setLayout(new GridLayout(1,1));
//                jpanel_pregun_pane.add(lblpregunta);             
            }}catch(SQLException | HeadlessException e){          
        } } 
    
//    ***************************************************************************************************
       
    void Confirmar_Respuesta(){
//        
          
        String  ced_trans = txtid.getText();
    //    String  pregunta = lblpregunta.getText();
        String  respuesta = txtRespuesta.getText();
        
        if(("".equals(ced_trans)) ||  ("".equals(respuesta)))
        {
            
            JOptionPane.showMessageDialog(null, "No pueden haber campos vacios");
            txtRespuesta.requestFocus();
            
        } else {
            
            if(Recuperacio.resp.equals(txtRespuesta.getText()))
            {
                
                dispose();
                
                CambioClave camb=new CambioClave();
                camb.setVisible(true);
                
                
            }else{
//                JOptionPane.showMessageDialog (null, "Respuesta Incorrecta");
//                txtRespuesta.setText("");
//                txtRespuesta.requestFocus();
                
            } 
        }
    }  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnconfirmar = new javax.swing.JButton();
        btnaceptar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        txtRespuesta = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnconfirmar.setText("Confirmar");
        btnconfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnconfirmarActionPerformed(evt);
            }
        });

        btnaceptar.setText("Aceptar");

        jLabel1.setText("RECUPERACION CONTRASEÑA");

        jLabel2.setText("USUARIO");

        jLabel3.setText("PREGUNTA DE SEGURIDAD ");

        jLabel4.setText("RESPUESTA");

        jLabel5.setText("¿COMO SE LLAMABA TU PRIMERA MASCOTA?");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtRespuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnaceptar)
                    .addComponent(btnconfirmar))
                .addGap(35, 35, 35))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnconfirmar)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtRespuesta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnaceptar))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnconfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnconfirmarActionPerformed
        // TODO add your handling code here:
        //         String ced_tra = txtusuario.getText();
//        try{
//            if ("".equals((ced_tra)))
//            {
//                    JOptionPane.showMessageDialog(null, "No pueden haber campos vacios");
//                    txtusuario.requestFocus();       
//            }else{
//
//                Connection cn= DriverManager.getConnection("jdbc:mysql://localhost/Usuarios","root","");   
////                String sql= "SELECT * FROM usuarios WHERE usuario='" + txtusuario.getText() + "'";
//////                                     Statement st=con.createStatement();
//            PreparedStatement pst = cn.prepareStatement("select * from usuarios where usaurio = ?");
//            pst.setString(1, txtusuario.getText().trim());
//            ResultSet rs = pst.executeQuery();
//
//        //    PreparedStatement pst = cn.prepareStatement("select * from usuarios where usuario = ?");
//         //   pst.setString(1, txtusuario.getText().trim());
//
//  //          ResultSet rs = pst.executeQuery();
//
//              //busca
//             //  ResultSet rs = st.executeQuery(sql);
//                String preg="";
//                String cedu="";
//                
//                if (rs.next()){
//                    //busca
//                   // cedu=rs.getString("usuario");
//                   // preg=rs.getString("pregunta");
//                    Recuperacio.resp = rs.getString("respuesta");
//                     
//                   
//                } else {
//                    JOptionPane.showConfirmDialog(null, "Nombre de Usuario Incorrecto");
//                    txtusuario.setText("");
//                    txtusuario.requestFocus();
//                }
 //**********************************************************************************************************
                //CONFIGURACION DE PREGUNTA EN EL PANEL 
//                Recuperacio.ced1=cedu;
//               
//                jpanel_pregun_pane.removeAll();
//                jpanel_pregun_pane.updateUI();
//                jpanel_pregun_pane.repaint();                
//                this.validate(); 
//                lblpregunta.setText(preg);
//                jpanel_pregun_pane.setLayout(new GridLayout(1,1));
//                jpanel_pregun_pane.add(lblpregunta);
//                         
//            }               
//        }catch(SQLException | HeadlessException e){          
//        } 
//
//        
//        
        //*******************************************************
        
//
//               try{
//            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/Usuarios", "root", "");
//            PreparedStatement pst = cn.prepareStatement("select * from usuarios where id = ?");
//            pst.setString(1, txtid.getText().trim());
//
//            ResultSet rs = pst.executeQuery();
//
//            if(rs.next()){
//                txtRespuesta.setText(rs.getString("respuesta"));
//                
//            } else {
//             JOptionPane.showMessageDialog(null, "Persona no registrada.");
//            }
//        }catch (Exception e){
//    } 
               
    }//GEN-LAST:event_btnconfirmarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Recuperacio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Recuperacio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Recuperacio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Recuperacio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Recuperacio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnaceptar;
    private javax.swing.JButton btnconfirmar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtRespuesta;
    private javax.swing.JTextField txtid;
    // End of variables declaration//GEN-END:variables
}
